version: "3"

services:
  app:
    build: .
    image: "citizensadvice/postcoder${POSTCODER_VERSION_TAG}"
    links:
      - cache
    ports:
      - 4000:4000
    volumes:
      - .:/app
    environment:
      - APP_ENV=development
      - API_KEY=PCW45-12345-12345-1234X
      - CACHE_URL=redis://cache:6379/1
      - CACHE_TTL=86400

  cache:
    image: redis:3.0.7
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru
