name: Run Tests

on:
  push:
    branches:
      - "*"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          docker build -t postcoder .
        
      - name: Lint
        run: |
          docker-compose run --rm app bundle exec rubocop

      - name: Test
        run: |
          docker-compose run -e APP_ENV=test --rm app bundle exec rspec